use_frameworks!

platform :ios, '9.0'

target 'SYSpecaPrivateTest_Example' do
  pod 'SYSpecaPrivateTest', :path => '../'

  target 'SYSpecaPrivateTest_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
